1. Write a NumPy program to reverse an array

In [1]:
import numpy as np
stringg = input("enter the elements of array separated by spaces: ")
array = np.fromstring(stringg ,dtype = float, sep=" ")
print(array)
i = 0
length = len(array)
for i in range(len(array)//2):
    tempp = array[i]
    array[i] = array[length-i-1]
    array[length-i-1] = tempp
print(array)



enter the elements of array separated by spaces: 1 2 3
[1. 2. 3.]
[3. 2. 1.]


2. Write a NumPy Program for finding the determinant of the 3D input matrix

In [2]:
first = input("Enter the first size ")
sec = input("Enter the second size ")
third = input("Enter the third size " )
matrix = np.zeros((int(first),int(sec),int(third)))
for i in range(int(first)):
    for j in range(int(sec)):
        for k in range(int(third)):
            matrix[i][j][k] = input("Enter the element ")
print(matrix)
print("The determinant of the matrix is ")
print(np.linalg.det(matrix))

Enter the first size 1
Enter the second size 2
Enter the third size 2
Enter the element 2
Enter the element 2
Enter the element 2
Enter the element 2
[[[2. 2.]
  [2. 2.]]]
The determinant of the matrix is 
[0.]


3.Write a numpy program for finding the traces of determinant

In [ ]:
row = input("Enter the number of rows ")
col = input("Enter the number of columns ")
matrix = np.zeros((int(row),int(col)))
for i in range(int(row)):
    for j in range(int(col)):
        matrix[i][j] = input("Enter the element ")
if i!=j:
    print("The matrix is not a square matrix")
else:
    print(matrix)
print("The trace of the matrix is ")
print(np.trace(matrix))

Enter the number of rows 3
Enter the number of columns 3
Enter the element 12
Enter the element 12
Enter the element 12
Enter the element 12
Enter the element 12
Enter the element 12
Enter the element 12
Enter the element 12
Enter the element 12
[[12. 12. 12.]
 [12. 12. 12.]
 [12. 12. 12.]]
The trace of the matrix is 
36.0


4. Create a Fibonacci series and find the sum of first 100 terms

In [7]:
def fibonacci_sum(n):

  f_list = [0, 1]
  if n <= 2:
      return sum(f_list[:n])

  for i in range(2, n):
      next_f = f_list[i - 1] + f_list[i - 2]
      f_list.append(next_f)

  return sum(f_list)


terms = 100
result = fibonacci_sum(terms)
print("The sum of the first 100 Fibonacci numbers is: ",fibonacci_sum(terms))

The sum of the first 100 Fibonacci numbers is:  573147844013817084100
